example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

mywatchlist/urls.py
from django.urls import path
from mywatchlist.views import show_json, show_json_by_id, show_mywatchlist, show_xml, show_xml_by_id, show_html

app_name = 'mywatchlist'

urlpatterns = [
    path('', show_mywatchlist, name='show_mywatchlist'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('xml/', show_xml, name='show_xml'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
    path('html/', show_html, name='show_html')
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

todolist/urls.py
from django.urls import path
from todolist.views import show_todolist, register_user, login_user, logout_user, create_task, delete_task, show_json, ajax_create_task

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register_user, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-task/', create_task, name='create-task'),
    path('delete/<int:id>', delete_task, name="delete_task"),
    path('json/', show_json, name='show_json'),
    path('add/', ajax_create_task, name='ajax_create_task'),
]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models

class MyWatchList(models.Model):
    watched = models.BooleanField()
    title = models.CharField(max_length=50)
    rating = models.FloatField()
    release_date = models.DateField()
    review = models.TextField()

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(auto_now = True)
    title = models.CharField(max_length=200)
    description = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from multiprocessing import context
from django.shortcuts import render
from katalog.models import CatalogItem

def show_katalog(request):
    data_katalog = CatalogItem.objects.all()
    context = {
        'list_katalog' : data_katalog,
        'nama'  : 'Bagas Shalahuddin Wahid',
        'npm'   : '2106708904'
    }
    return render(request, "katalog.html", context)

mywatchlist/views.py
from email import message
from django.shortcuts import render
from mywatchlist.models import MyWatchList
from django.http import HttpResponse
from django.core import serializers

def show_mywatchlist(request):
    return HttpResponse("Tugas 3 PBP")

def show_xml(request):
    data_mywatchlist = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("xml", data_mywatchlist), content_type="application/xml")

def show_json(request):
    data_mywatchlist = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("json", data_mywatchlist), content_type="application/json")

def show_json_by_id(request, id):
    data_mywatchlist = MyWatchList.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data_mywatchlist), content_type="application/json")

def show_xml_by_id(request, id):
    data_mywatchlist = MyWatchList.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data_mywatchlist), content_type="application/xml")

def show_html(request):
    data_mywatchlist = MyWatchList.objects.all()
    
    watched = 0
    
    for film in data_mywatchlist:
        if film.watched == True:
            watched += 1
    
    if watched >= 5:
        message = "Selamat, kamu sudah banyak menonton!"
    else:
        message = "Wah, kamu masih sedikit menonton!"
        
    context = {
        'list_mywatchlist': data_mywatchlist,
        'nama': 'Bagas',
        'npm' : '2106708904',
        'message' : message
    }
    return render(request, "mywatchlist.html", context)

todolist/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core import serializers
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
import datetime

from todolist.models import Task

@login_required(login_url='/todolist/login/')
def show_todolist(request):
    username = request.user.username
    list_task = Task.objects.filter(user=request.user)
    context = { 
        "username": username,
        "todolist": list_task,
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "todolist.html", context)

@login_required(login_url='/todolist/login/')
def show_json(request):
    todolist = Task.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", todolist), content_type="application/json")

@login_required(login_url='/todolist/login/')
def create_task(request):
    context = {}
    if request.method == "POST":
        title = request.POST.get("title")
        description = request.POST.get("description")
        new_task = Task(user = request.user, title = title, description = description)
        new_task.save()
        return redirect("todolist:show_todolist")
    
    return render(request, "create-task.html", context)

@csrf_exempt
@login_required(login_url='/todolist/login/')
def ajax_create_task(request):
    if request.method == "POST":
        title = request.POST.get("title")
        description = request.POST.get("description")
        Task.objects.create(user = request.user, title = title, description = description)

        return JsonResponse({
            "title" : title,
            "description" : description
        }, status=200)

def register_user(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("todolist:show_todolist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.warning(request, 'Username or Password incorrect!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

def delete_task(request, id):
    task = Task.objects.get(pk=id)
    task.delete()
    return HttpResponseRedirect("/todolist/")

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Lab 1 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{npm}}</p>

  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for katalog in list_katalog %}
    <tr>
        <th>{{katalog.item_name}}</th>
        <th>{{katalog.item_price}}</th>
        <th>{{katalog.description}}</th>
        <th>{{katalog.item_stock}}</th>
        <th>{{katalog.rating}}</th>
        <th>{{katalog.item_url}}</th>
    </tr>
{% endfor %}
  </table>

 {% endblock content %}

mywatchlist/templates/mywatchlist.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Tugas 3 PBP/PBD</h1>

  <h3>Name: {{nama}}</h5>

  <h3>Student ID: {{npm}} </h3>

  <br></br>
  
  <h2 style="text-align: center;">My Watch List</h2>
  <h2 style="color:blue; text-align: center;"> {{message}}</h2>
  
  <br></br>
  <br></br>

  <table style="width:100%">
    <tr>
      <th style="width: 5%">Watched</th>
      <th style="width:15%">Title</th>
      <th style="width: 5%">Rating</th>
      <th style="width:10%">Release Date</th>
      <th style="width: 65%">Review</th>
    </tr>

    {% comment %} Add the data below this line {% endcomment %}
    {% for mywatchlist in list_mywatchlist %}
    <tr>
        {% if mywatchlist.watched %}
        <td style="text-align:center">Sudah</td>
        {% else %}
        <td style="text-align:center">Belum</td>
        {% endif %}

        <td style="text-align:center">{{mywatchlist.title}}</td>
        <td style="text-align:center">{{mywatchlist.rating}}</td>
        <td style="text-align:center">{{mywatchlist.release_date}}</td>
        <td style="text-align:justify">{{mywatchlist.review}}</td>

    </tr>
{% endfor %}
  </table>

 {% endblock content %}

<!-- https://www.w3schools.com/html/html_table_sizes.asp --> 
<!-- https://blog.hubspot.com/website/html-space -->
<!-- https://stackoverflow.com/questions/72547200/how-to-set-an-if-statement-to-true-in-a-django-template -->
<!-- https://www.tutorialspoint.com/How-to-center-align-text-in-table-cells-in-HTML -->

templates/base.html
  {% load static %}
  <!DOCTYPE html>
  <html lang="en">

  <head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}"> 
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>

</html>

todolist/templates/create-task.html
{% extends 'base.html' %}

{% block meta %}
<title>Create Task</title>
{% endblock meta %}

{% block content %}
<div class="vh-100" style="background-color: #60c7cb;">
    <div class="container py-5 h-100">
        <div class="d-flex justify-content-center align-items-center h-100">
            <div class="col col-xl-10">
                <div class="card" style="border-radius: 1rem;">
                    <div class="col-md-12 col-lg-15 d-flex align-items-center">
                        <div class="card-body p-4 p-lg-5 text-black">

                            <form method="POST" action="">
                                {% csrf_token %}

                                <div class="d-flex align-items-center mb-3 pb-1">
                                    <label class="h1 fw-bold mb-0">Create Task</label>
                                </div>
            
                                <div class="form-outline mb-4">
                                    <input type="title" name = "title" id="formtitle" class="form-control form-control-lg" />
                                    <label class="form-label" for="formtitle">Title</label>
                                </div>

                                <div class="form-outline mb-4">
                                    <textarea type="description" name = "description" id="formdescription" class="form-control form-control-lg"></textarea>
                                    <label class="form-label" for="formdescription">Description</label>
                                </div>

                                <div class="pt-1 mb-4" style="margin: auto;">
                                    <button class="btn btn-success btn-lg btn-block" type="submit">Add</button>
                                </div>
                            </form>
                        </div>    
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}
<div class="vh-100" style="background-color: #60c7cb;">
    <div class="container py-5 h-100">
        <div class="d-flex justify-content-center align-items-center h-100">
            <div class="col col-xl-10">
                <div class="card" style="border-radius: 1rem;">
                    <div class="row g-0">
                        <div class="col-md-6 col-lg-5 d-none d-md-block py-5">
                            <img src="https://i.ibb.co/b1tTPqm/todolist.webp"
                            alt="todolist_login_form" class="img-fluid" style="border-radius: 1rem 0 0 1rem; " />
                        </div>

                        <div class="col-md-6 col-lg-7 d-flex align-items-center">
                            <div class="card-body p-4 p-lg-5 text-black">

                                <form method="POST" action="">
                                {% csrf_token %}

                                <div class="d-flex align-items-center mb-3 pb-1">
                                    <label class="h1 fw-bold mb-0">Login</label>
                                </div>
            
                                <div class="form-outline mb-4">
                                    <input type="username" name = "username" id="formUsername" class="form-control form-control-lg" />
                                    <label class="form-label" for="formUsername">Username</label>
                                </div>
            
                                <div class="form-outline mb-4">
                                    <input type="password"  name="password"  id="formPassword" class="form-control form-control-lg" />
                                    <label class="form-label" for="formPassword">Password</label>
                                </div>
            
                                <div class="pt-1 mb-4">
                                    <button class="btn btn-dark btn-lg btn-block" type="submit">Login</button>
                                </div>
            
                                <p class="mb-5 pb-2" style="color: #393f81;">Don't have an account? <a href="{% url 'todolist:register' %}"
                                    style="color: #393f81;">Register here</a></p>
                                </form>

                                {% if messages %}
                                    <ul>
                                        {% for message in messages %}
                                            <li class="pb-2" style="color: #393f81;" >{{ message }}</li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}     
  
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Register</title>
{% endblock meta %}

{% block content %}
<div class="vh-100" style="background-color: #60c7cb;">
    <div class="container py-5 h-100">
        <div class="d-flex justify-content-center align-items-center h-100">
            <div class="col col-xl-10">
                <div class="card" style="border-radius: 1rem;">
                    <div class="col-md-12 col-lg-15 d-flex align-items-center">
                        <div class="card-body p-4 p-lg-5 text-black">

                            <form method="POST" action="">
                                {% csrf_token %}

                                <div class="d-flex align-items-center mb-3 pb-1">
                                    <label class="h1 fw-bold mb-0">Registration Form</label>
                                </div>
            
                                <div class="mb-4">
                                    {{ form.username.label_tag }}
                                    {{ form.username}}
                                </div>

                                <div class="form-outline mb-4">
                                    {{ form.password1.label_tag }}
                                    {{ form.password1 }}
                                </div>

                                <div class="form-outline mb-4">
                                    {{ form.password2.label_tag }}
                                    {{ form.password2 }}
                                </div>

                                <div class="pt-1 mb-4">
                                    <button class="btn btn-dark btn-lg btn-block" type="submit">Daftar</button>
                                </div>
                                
                                {% if messages %}  
                                <ul>   
                                    {% for message in messages %}  
                                        <li class="pb-2" style="color: #393f81;">{{ message }}</li>  
                                        {% endfor %}  
                                </ul>   
                                {% endif %}
                                   
                            </form>
                        </div>   
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block meta %}
<title>Todolist Apps</title>
{% endblock meta %}

{% block content %}
<style type="text/css">
  
  body {
    background: #60c7cb;
    padding: auto;
  }
  
  .card {
    background: #222;
    border: 1px solid #0b090a;
    color: rgba(250, 250, 250, 0.8);
    margin-bottom: 2rem;
  }
  
  .btn-warning {
    color:yellow;
    background-color: white;
    border-color: white;
  }
  
  .zoom:hover {
    transform: scale(1.05);
  }
  
  textarea {
    max-width: 100%;
  }

</style>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
$(document).ready(function(){
  $.getJSON("{% url 'todolist:show_json' %}", function(data) {
    $.each(data, function(index, value) {
      console.log(value)
      $("#todolistCard").append(`
        <div class="card text-center zoom">
          <div class="card-header card-bg-rv"> Date Created: ${value.fields.date} </div>
          <div class="image-box card-bg-rv">
            <img src="https://i.ibb.co/b1tTPqm/todolist.webp" height="200"></img>
            <div class="card responsive-card">
            <div class="card-body card-bg-rv">
              <h5 class="card-title"> ${value.fields.title} </h5>
              <p class="card-text"> ${value.fields.description} </p>
            </div>
          </div>
          </div>
        </div>`
      )
    })
  })

  $("#createTaskForm").on("submit", function(e){
    e.preventDefault();
    var date = new Date();
    var current_date = date.getFullYear() + "-" + (date.getMonth()+1) + "-" +date.getDate();
    var title = $("#title").val();
    var description= $("#description").val();
   
    $.ajax({
      method: "POST",
      url: "/todolist/add/",  
      data: {"title":title, "description":description},
    }).done(function(resp) {
      console.log(resp)
      $("#todolistCard").append(`
        <div class="card text-center zoom">
          <div class="card-header card-bg-rv"> Date Created: ${current_date} </div>
          <div class="image-box card-bg-rv">
            <img src="https://i.ibb.co/b1tTPqm/todolist.webp" height="200"></img>
            <div class="card responsive-card">
            <div class="card-body card-bg-rv">
              <h5 class="card-title"> ${resp.title} </h5>
              <p class="card-text"> ${resp.description} </p>
            </div>
          </div>
          </div>
        </div>`
      )
      $("#createTaskModal").modal("hide")
    })
  })
})
</script>

<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand">Hi, Welcome {{username}}</a>
  <form class="form-inline">
    <button class="btn btn-warning my-2 my-sm-0" type="submit"><a href="{% url 'todolist:create-task' %}">Create Task</a></button>
    <button class="btn btn-danger my-2 my-sm-0" type="submit"><a href="{% url 'todolist:logout' %}">Logout</a></button>
  </form>
</nav>

<div class="d-flex flex-wrap justify-content-center align-items-center py-5">
  <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#createTaskModal" >Create Task</button>

  <div class="modal fade" id="createTaskModal" tabindex="-1" aria-labelledby="createTaskModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="createTaskModalLabel">Create Task</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form method="POST" action="/todolist/add/" id="createTaskForm">
            {% csrf_token %}
            <div class="mb-3">
              <label for="title" class="col-form-label">Title</label>
              <input type="text" class="form-control" id="title" required>
            </div>
            <div class="mb-3">
              <label for="description" class="col-form-label">Description</label>
              <textarea class="text" id="description" cols="50" rows="10" required></textarea>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary" data-bs-dismiss="modal" id="tambahTask">Tambah</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="d-flex flex-wrap justify-content-center align-items-center gap-5 responsive-container py-5" id = "todolistCard">
</div>

{% endblock content %}